apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-watcher-sa
  namespace: shmfaas

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-watcher-cr
  namespace: shmfaas
rules:
- apiGroups: [ "metrics.k8s.io" ]
  resources: [ "pods", "podmetrices" ]
  verbs: [ "get", "list", "watch" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-watcher-crb
subjects:
- kind: ServiceAccount
  name: metrics-watcher-sa
  namespace: shmfaas
roleRef:
  kind: ClusterRole
  name: metrics-watcher-cr
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-watcher-config
  namespace: shmfaas
data:
  metrics-watcher-config.yaml: |
    namespace: shmfaas

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-watcher
  namespace: shmfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-watcher
  template:
    metadata:
      labels:
        app: metrics-watcher
    spec:
      serviceAccount: metrics-watcher-sa
      containers:
      - name: metrics-watcher
        image: ghcr.io/freckie/k8s-metrics-watcher:0.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          hostPort: 9102
          protocol: TCP
        env:
        - name: CONFIG
          value: /etc/metrics-watcher/metrics-watcher-config.yaml
        volumeMounts:
        - name: metrics-watcher-vol
          mountPath: /etc/metrics-watcher
          readOnly: true
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
            scheme: HTTP
      volumes:
      - name: metrics-watcher-vol
        configMap:
          name: metrics-watcher-config
      nodeName: dnclab3
