apiVersion: v1
kind: Namespace
metadata:
  name: shmfaas

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: shmm-daemon
  namespace: shmfaas
  labels:
    k8s-app: shmm
spec:
  selector:
    matchLabels:
      name: shmm-pod
  template:
    metadata:
      labels:
        name: shmm-pod
    spec:
      hostIPC: true
      containers:
      - name: shmm-pod
        image: ghcr.io/freckie/shmm:0.0.2
        env:
        - name: PORT
          value: "20000"
        - name: SQLITE3
          value: "shmm.db3"
        ports:
        - containerPort: 20000
          hostPort: 20000
          protocol: TCP
